spring:
  datasource:
    url: jdbc:postgresql://db:5432/eeze_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:postgresql://db:5432/eeze_db
    user: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
